"""create_tables

Revision ID: e41f1bd21b17
Revises: 7b08d6d37ff1
Create Date: 2025-06-07 17:48:09.546994

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e41f1bd21b17'
down_revision: Union[str, None] = '7b08d6d37ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'article',
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('parsed_text', sa.String(), nullable=False),
        sa.Column('summary', sa.String(), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url'),
    )
    op.create_index('article_url_idx', 'article', ['url'], unique=False, postgresql_using='hash')
    op.create_table(
        'article_to_articles',
        sa.Column('parent_id', sa.Uuid(), nullable=False),
        sa.Column('sibling_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['article.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sibling_id'],
            ['article.id'],
        ),
        sa.PrimaryKeyConstraint('parent_id', 'sibling_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_to_articles')
    op.drop_index('article_url_idx', table_name='article', postgresql_using='hash')
    op.drop_table('article')
    # ### end Alembic commands ###
